package com.softwareag.is.wmscript.compiler;

import com.softwareag.is.wmscript.compiler.parser.WmScriptParser;
import com.softwareag.is.wmscript.compiler.parser.WmScriptParser.*;
import com.softwareag.is.wmscript.compiler.parser.WmScriptBaseVisitor;

import java.util.*;

/**
 * Visits the WmScript parse tree and generates Java source code.
 * The generated code uses PipelineContext as the runtime helper.
 */
public class JavaCodeGenerator extends WmScriptBaseVisitor<String> {

    private final String className;
    private final String packageName;
    private final StringBuilder imports = new StringBuilder();
    private int indent = 2; // start inside method body
    private int tempVarCounter = 0;
    private final Set<String> localVars = new HashSet<>();

    /** Source map: generated Java line number -> original .wms line number */
    private final Map<Integer, Integer> sourceMap = new LinkedHashMap<>();
    private int currentJavaLine = 1; // tracks which Java line we're generating
    private String sourceFileName = "service.wms";

    public JavaCodeGenerator(String className, String packageName) {
        this.className = className;
        this.packageName = packageName;
    }

    public void setSourceFileName(String fileName) {
        this.sourceFileName = fileName;
    }

    /** Get the source map (Java line -> WmScript line) */
    public Map<Integer, Integer> getSourceMap() {
        return Collections.unmodifiableMap(sourceMap);
    }

    private String newTempVar(String prefix) {
        return "_" + prefix + "_" + (++tempVarCounter);
    }

    private String indent() {
        return "    ".repeat(indent);
    }

    /** Emit a source line marker comment and track it in the source map */
    private String lineMarker(org.antlr.v4.runtime.ParserRuleContext ctx) {
        if (ctx == null || ctx.getStart() == null) return "";
        int wmsLine = ctx.getStart().getLine();
        // The marker comment will be on the next Java line we emit
        String marker = indent() + "// @wms:" + wmsLine + "\n";
        // Count lines in the marker itself
        currentJavaLine++;
        sourceMap.put(currentJavaLine, wmsLine);
        return marker;
    }

    /** Count newlines in a string to track Java line numbers */
    private void trackLines(String code) {
        for (int i = 0; i < code.length(); i++) {
            if (code.charAt(i) == '\n') currentJavaLine++;
        }
    }

    public String generate(ProgramContext tree) {
        // Build header first to know the starting line for body code
        StringBuilder header = new StringBuilder();
        header.append("// Generated by WmScript compiler — DO NOT EDIT\n");
        header.append("// Source: ").append(sourceFileName).append("\n");
        if (packageName != null && !packageName.isEmpty()) {
            header.append("package ").append(packageName).append(";\n\n");
        }
        header.append("import com.wm.data.*;\n");
        header.append("import com.wm.app.b2b.server.ServiceException;\n");
        header.append("import com.softwareag.is.wmscript.runtime.PipelineContext;\n");
        header.append("import static com.softwareag.is.wmscript.runtime.PipelineContext.*;\n\n");
        header.append("public class ").append(className).append(" {\n\n");
        header.append("    public static void main(IData pipeline) throws Exception {\n");
        header.append("        PipelineContext ctx = new PipelineContext(pipeline);\n\n");

        // Count header lines so source map is accurate
        currentJavaLine = 1;
        trackLines(header.toString());

        // Visit all statements
        StringBuilder body = new StringBuilder();
        for (StatementContext stmt : tree.statement()) {
            String marker = lineMarker(stmt);
            String code = visit(stmt);
            if (code != null && !code.isEmpty()) {
                body.append(marker);
                body.append(code);
                trackLines(code);
            }
        }

        String footer = "\n        ctx.finalizeLists();\n    }\n}\n";

        return header.toString() + body.toString() + footer;
    }

    // ============================================================
    // Statements
    // ============================================================

    @Override
    public String visitSimpleAssignment(SimpleAssignmentContext ctx) {
        String targetStr = ctx.target().getText();
        String exprCode = visit(ctx.expression());

        if (targetStr.contains(".")) {
            // Nested field assignment: order.customer.name = value
            return generateNestedSet(targetStr, exprCode);
        }

        if (localVars.contains(targetStr)) {
            return indent() + targetStr + " = " + exprCode + ";\n";
        }

        // First assignment to a non-dotted name could be local or pipeline
        // We treat top-level names as pipeline variables
        return indent() + "ctx.set(\"" + escape(targetStr) + "\", " + exprCode + ");\n";
    }

    @Override
    public String visitDestructureAssignment(DestructureAssignmentContext ctx) {
        String exprCode = visit(ctx.expression());
        String tempVar = newTempVar("result");
        StringBuilder sb = new StringBuilder();
        sb.append(indent()).append("IData ").append(tempVar).append(" = (IData) ").append(exprCode).append(";\n");

        for (var id : ctx.IDENTIFIER()) {
            String name = id.getText();
            sb.append(indent()).append("ctx.set(\"").append(escape(name))
              .append("\", PipelineContext.extract(").append(tempVar).append(", \"")
              .append(escape(name)).append("\"));\n");
        }
        return sb.toString();
    }

    @Override
    public String visitAppendStatement(AppendStatementContext ctx) {
        String targetStr = ctx.target().getText();
        String exprCode = visit(ctx.expression());
        return indent() + "ctx.appendToList(\"" + escape(targetStr) + "\", " + exprCode + ");\n";
    }

    @Override
    public String visitInvokeStatement(InvokeStatementContext ctx) {
        // Invoke without assignment → merge output into current pipeline
        String tempVar = newTempVar("out");
        return indent() + "IData " + tempVar + " = (IData) "
             + generateInvokeCall(ctx.serviceRef(), ctx.argumentList()) + ";\n"
             + indent() + "if (" + tempVar + " != null) { com.wm.data.IDataUtil.merge("
             + tempVar + ", pipeline); }\n";
    }

    @Override
    public String visitIfStatement(IfStatementContext ctx) {
        StringBuilder sb = new StringBuilder();

        String cond = visit(ctx.expression());
        sb.append(indent()).append("if (toBoolean(").append(cond).append(")) {\n");
        indent++;
        sb.append(visitBlock(ctx.block()));
        indent--;
        sb.append(indent()).append("}");

        for (ElifClauseContext elif : ctx.elifClause()) {
            String elifCond = visit(elif.expression());
            sb.append(" else if (toBoolean(").append(elifCond).append(")) {\n");
            indent++;
            sb.append(visitBlock(elif.block()));
            indent--;
            sb.append(indent()).append("}");
        }

        if (ctx.elseClause() != null) {
            sb.append(" else {\n");
            indent++;
            sb.append(visitBlock(ctx.elseClause().block()));
            indent--;
            sb.append(indent()).append("}");
        }

        sb.append("\n");
        return sb.toString();
    }

    @Override
    public String visitForStatement(ForStatementContext ctx) {
        List<org.antlr.v4.runtime.tree.TerminalNode> ids = ctx.IDENTIFIER();
        String iterExpr = visit(ctx.expression());
        String iterVar = newTempVar("iter");
        String idxVar = newTempVar("i");

        StringBuilder sb = new StringBuilder();

        if (ids.size() == 2) {
            // Two-variable form: for key, value in entries(doc):
            String keyVar = ids.get(0).getText();
            String valVar = ids.get(1).getText();

            sb.append(indent()).append("IData[] ").append(iterVar)
              .append(" = PipelineContext.toEntryArray(").append(iterExpr).append(");\n");
            sb.append(indent()).append("for (int ").append(idxVar).append(" = 0; ")
              .append(idxVar).append(" < ").append(iterVar).append(".length; ")
              .append(idxVar).append("++) {\n");
            indent++;
            sb.append(indent()).append("Object ").append(keyVar)
              .append(" = PipelineContext.getField(").append(iterVar).append("[").append(idxVar).append("], \"key\");\n");
            sb.append(indent()).append("Object ").append(valVar)
              .append(" = PipelineContext.getField(").append(iterVar).append("[").append(idxVar).append("], \"value\");\n");
            localVars.add(keyVar);
            localVars.add(valVar);
            sb.append(visitBlock(ctx.block()));
            localVars.remove(keyVar);
            localVars.remove(valVar);
        } else {
            // Single variable form: for item in collection:
            String varName = ids.get(0).getText();

            sb.append(indent()).append("Object[] ").append(iterVar)
              .append(" = toIterable(").append(iterExpr).append(");\n");
            sb.append(indent()).append("for (int ").append(idxVar).append(" = 0; ")
              .append(idxVar).append(" < ").append(iterVar).append(".length; ")
              .append(idxVar).append("++) {\n");
            indent++;
            sb.append(indent()).append("Object ").append(varName).append(" = ")
              .append(iterVar).append("[").append(idxVar).append("];\n");
            localVars.add(varName);
            sb.append(visitBlock(ctx.block()));
            localVars.remove(varName);
        }

        indent--;
        sb.append(indent()).append("}\n");
        return sb.toString();
    }

    @Override
    public String visitWhileStatement(WhileStatementContext ctx) {
        String cond = visit(ctx.expression());
        StringBuilder sb = new StringBuilder();
        sb.append(indent()).append("while (toBoolean(").append(cond).append(")) {\n");
        indent++;
        sb.append(visitBlock(ctx.block()));
        indent--;
        sb.append(indent()).append("}\n");
        return sb.toString();
    }

    @Override
    public String visitTryStatement(TryStatementContext ctx) {
        String exVar = ctx.catchClause().IDENTIFIER().getText();
        StringBuilder sb = new StringBuilder();
        sb.append(indent()).append("try {\n");
        indent++;
        sb.append(visitBlock(ctx.block()));
        indent--;
        sb.append(indent()).append("} catch (Exception ").append(exVar).append(") {\n");
        indent++;
        localVars.add(exVar);
        sb.append(visitBlock(ctx.catchClause().block()));
        localVars.remove(exVar);
        indent--;
        sb.append(indent()).append("}\n");
        return sb.toString();
    }

    @Override
    public String visitRaiseStatement(RaiseStatementContext ctx) {
        String exprCode = visit(ctx.expression());
        return indent() + "throw new ServiceException(PipelineContext.toStr(" + exprCode + "));\n";
    }

    @Override
    public String visitReturnStatement(ReturnStatementContext ctx) {
        if (ctx.expression() != null) {
            String exprCode = visit(ctx.expression());
            return indent() + "ctx.set(\"$return\", " + exprCode + ");\n"
                 + indent() + "return;\n";
        }
        return indent() + "return;\n";
    }

    @Override
    public String visitLogStatement(LogStatementContext ctx) {
        String level = ctx.logLevel().getText();
        String exprCode = visit(ctx.expression());
        // Map to IS JournalLogger
        String logMethod;
        switch (level) {
            case "error": logMethod = "logError"; break;
            case "warn":  logMethod = "logWarn"; break;
            case "info":  logMethod = "logInfo"; break;
            case "debug": logMethod = "logDebug"; break;
            default:      logMethod = "logInfo";
        }
        return indent() + "PipelineContext." + logMethod
             + "(PipelineContext.toStr(" + exprCode + "));\n";
    }

    @Override
    public String visitSkipStatement(SkipStatementContext ctx) {
        return indent() + "continue;\n";
    }

    @Override
    public String visitBreakStatement(BreakStatementContext ctx) {
        return indent() + "break;\n";
    }

    @Override
    public String visitContinueStatement(ContinueStatementContext ctx) {
        return indent() + "continue;\n";
    }

    @Override
    public String visitBlock(BlockContext ctx) {
        StringBuilder sb = new StringBuilder();
        for (StatementContext stmt : ctx.statement()) {
            String marker = lineMarker(stmt);
            String code = visit(stmt);
            if (code != null && !code.isEmpty()) {
                sb.append(marker);
                sb.append(code);
                trackLines(marker + code);
            }
        }
        return sb.toString();
    }

    // ============================================================
    // Expressions
    // ============================================================

    @Override
    public String visitInvokeExpr(InvokeExprContext ctx) {
        InvokeExpressionContext invoke = ctx.invokeExpression();
        return generateInvokeCall(invoke.serviceRef(), invoke.argumentList());
    }

    @Override
    public String visitDotAccess(DotAccessContext ctx) {
        String left = visit(ctx.expression());
        String field = ctx.IDENTIFIER().getText();
        return "PipelineContext.getField(" + left + ", \"" + escape(field) + "\")";
    }

    @Override
    public String visitNullSafeAccess(NullSafeAccessContext ctx) {
        String left = visit(ctx.expression());
        String field = ctx.IDENTIFIER().getText();
        return "PipelineContext.getFieldSafe(" + left + ", \"" + escape(field) + "\")";
    }

    @Override
    public String visitArrayProjection(ArrayProjectionContext ctx) {
        String left = visit(ctx.expression());
        String field = ctx.IDENTIFIER().getText();
        return "PipelineContext.project(" + left + ", \"" + escape(field) + "\")";
    }

    @Override
    public String visitIndexAccess(IndexAccessContext ctx) {
        String left = visit(ctx.expression(0));
        String index = visit(ctx.expression(1));
        return "arrayGet(" + left + ", " + index + ")";
    }

    @Override
    public String visitFilterAccess(FilterAccessContext ctx) {
        String left = visit(ctx.expression(0));
        String field = ctx.IDENTIFIER().getText();
        String value = visit(ctx.expression(1));
        return "PipelineContext.filter(" + left + ", \"" + escape(field) + "\", " + value + ")";
    }

    @Override
    public String visitNullCoalesceExpr(NullCoalesceExprContext ctx) {
        String left = visit(ctx.expression(0));
        String right = visit(ctx.expression(1));
        return "PipelineContext.coalesce(" + left + ", " + right + ")";
    }

    @Override
    public String visitTernaryExpr(TernaryExprContext ctx) {
        String cond = visit(ctx.expression(0));
        String trueVal = visit(ctx.expression(1));
        String falseVal = visit(ctx.expression(2));
        return "(toBoolean(" + cond + ") ? " + trueVal + " : " + falseVal + ")";
    }

    @Override
    public String visitComparisonExpr(ComparisonExprContext ctx) {
        String left = visit(ctx.expression(0));
        String right = visit(ctx.expression(1));
        String op = ctx.getChild(1).getText();
        switch (op) {
            case "==": return "eq(" + left + ", " + right + ")";
            case "!=": return "!eq(" + left + ", " + right + ")";
            case "<":  return "cmp(" + left + ", " + right + ") < 0";
            case ">":  return "cmp(" + left + ", " + right + ") > 0";
            case "<=": return "cmp(" + left + ", " + right + ") <= 0";
            case ">=": return "cmp(" + left + ", " + right + ") >= 0";
            default:   return left + " " + op + " " + right;
        }
    }

    @Override
    public String visitAndExpr(AndExprContext ctx) {
        return "toBoolean(" + visit(ctx.expression(0)) + ") && toBoolean(" + visit(ctx.expression(1)) + ")";
    }

    @Override
    public String visitOrExpr(OrExprContext ctx) {
        return "toBoolean(" + visit(ctx.expression(0)) + ") || toBoolean(" + visit(ctx.expression(1)) + ")";
    }

    @Override
    public String visitNotExpr(NotExprContext ctx) {
        return "!toBoolean(" + visit(ctx.expression()) + ")";
    }

    @Override
    public String visitAddSubExpr(AddSubExprContext ctx) {
        String left = visit(ctx.expression(0));
        String right = visit(ctx.expression(1));
        String op = ctx.getChild(1).getText();
        if ("+".equals(op)) {
            return "add(" + left + ", " + right + ")";
        }
        return "PipelineContext.toNum(" + left + ") " + op + " PipelineContext.toNum(" + right + ")";
    }

    @Override
    public String visitMulDivExpr(MulDivExprContext ctx) {
        String left = visit(ctx.expression(0));
        String right = visit(ctx.expression(1));
        String op = ctx.getChild(1).getText();
        return "PipelineContext.toNum(" + left + ") " + op + " PipelineContext.toNum(" + right + ")";
    }

    @Override
    public String visitStringLiteral(StringLiteralContext ctx) {
        return ctx.getText();
    }

    @Override
    public String visitTemplateString(TemplateStringContext ctx) {
        // f"Hello {name}, total: {order.amount + tax}" -> string concatenation with compiled expressions
        String raw = ctx.getText();
        // Remove f" prefix and " suffix
        raw = raw.substring(2, raw.length() - 1);
        StringBuilder sb = new StringBuilder("\"\"");
        int i = 0;
        while (i < raw.length()) {
            if (raw.charAt(i) == '{') {
                int end = findMatchingBrace(raw, i);
                String exprText = raw.substring(i + 1, end);
                // Re-parse the expression through the WmScript compiler
                String compiledExpr = WmScriptCompiler.compileExpression(exprText);
                sb.append(" + PipelineContext.toStr(").append(compiledExpr).append(")");
                i = end + 1;
            } else {
                int next = raw.indexOf('{', i);
                if (next < 0) next = raw.length();
                sb.append(" + \"").append(escape(raw.substring(i, next))).append("\"");
                i = next;
            }
        }
        return sb.toString();
    }

    /** Find the matching '}' for a '{', handling nested braces */
    private int findMatchingBrace(String s, int openPos) {
        int depth = 0;
        for (int i = openPos; i < s.length(); i++) {
            if (s.charAt(i) == '{') depth++;
            else if (s.charAt(i) == '}') {
                depth--;
                if (depth == 0) return i;
            }
        }
        return s.length(); // fallback: end of string
    }

    @Override
    public String visitNumberLiteral(NumberLiteralContext ctx) {
        String text = ctx.getText();
        if (text.contains(".")) {
            return text;
        }
        return text;
    }

    @Override
    public String visitTrueLiteral(TrueLiteralContext ctx) {
        return "Boolean.TRUE";
    }

    @Override
    public String visitFalseLiteral(FalseLiteralContext ctx) {
        return "Boolean.FALSE";
    }

    @Override
    public String visitNullLiteral(NullLiteralContext ctx) {
        return "null";
    }

    @Override
    public String visitPipelineLiteral(PipelineLiteralContext ctx) {
        return "pipeline";
    }

    @Override
    public String visitDocumentLiteral(DocumentLiteralContext ctx) {
        StringBuilder sb = new StringBuilder("PipelineContext.createDocument(");
        boolean first = true;
        for (DocumentEntryContext entry : ctx.documentEntry()) {
            if (!first) sb.append(", ");
            // Key can be IDENTIFIER or STRING_LITERAL
            String key = entry.IDENTIFIER() != null
                ? "\"" + escape(entry.IDENTIFIER().getText()) + "\""
                : entry.STRING_LITERAL().getText();
            sb.append(key).append(", ").append(visit(entry.expression()));
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String visitArrayLiteral(ArrayLiteralContext ctx) {
        StringBuilder sb = new StringBuilder("new Object[] {");
        boolean first = true;
        for (ExpressionContext expr : ctx.expression()) {
            if (!first) sb.append(", ");
            sb.append(visit(expr));
            first = false;
        }
        sb.append("}");
        return sb.toString();
    }

    @Override
    public String visitVariableExpr(VariableExprContext ctx) {
        String name = ctx.target().getText();
        // Check if it has dots -> nested access
        List<String> parts = new ArrayList<>();
        for (var id : ctx.target().IDENTIFIER()) {
            parts.add(id.getText());
        }

        if (parts.size() == 1) {
            String varName = parts.get(0);
            if (localVars.contains(varName)) {
                return varName;
            }
            return "ctx.get(\"" + escape(varName) + "\")";
        }

        // Multi-part: order.customer.name -> PipelineContext.getPath(ctx.get("order"), "customer", "name")
        StringBuilder sb = new StringBuilder();
        String root = parts.get(0);
        if (localVars.contains(root)) {
            sb.append("PipelineContext.getPath(").append(root);
        } else {
            sb.append("PipelineContext.getPath(ctx.get(\"").append(escape(root)).append("\")");
        }
        for (int i = 1; i < parts.size(); i++) {
            sb.append(", \"").append(escape(parts.get(i))).append("\"");
        }
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String visitParenExpr(ParenExprContext ctx) {
        return "(" + visit(ctx.expression()) + ")";
    }

    @Override
    public String visitBuiltinExpr(BuiltinExprContext ctx) {
        return visitBuiltinCall(ctx.builtinCall());
    }

    @Override
    public String visitBuiltinCall(BuiltinCallContext ctx) {
        String name = ctx.builtinName().getText();
        List<String> args = new ArrayList<>();
        for (ExpressionContext expr : ctx.expression()) {
            args.add(visit(expr));
        }

        switch (name) {
            case "num":    return "PipelineContext.toNum(" + args.get(0) + ")";
            case "str":    return "PipelineContext.toStr(" + args.get(0) + ")";
            case "int":    return "PipelineContext.toInt(" + args.get(0) + ")";
            case "date":   return "PipelineContext.toDate(" + args.get(0) + ", " + args.get(1) + ")";
            case "len":    return "PipelineContext.len(" + args.get(0) + ")";
            case "sum":    return "PipelineContext.sum(" + args.get(0) + ")";
            case "min":    return "PipelineContext.min(" + args.get(0) + ")";
            case "max":    return "PipelineContext.max(" + args.get(0) + ")";
            case "join":   return "PipelineContext.join(" + args.get(0) + ", " + args.get(1) + ")";
            case "split":  return "PipelineContext.split(" + args.get(0) + ", " + args.get(1) + ")";
            case "keys":     return "PipelineContext.keys(" + args.get(0) + ")";
            case "values":   return "PipelineContext.values(" + args.get(0) + ")";
            case "entries":  return "PipelineContext.entries(" + args.get(0) + ")";
            case "exists":   return "ctx.exists(" + args.get(0) + ")";
            case "typeof":   return "PipelineContext.typeOf(" + args.get(0) + ")";
            case "contains": return "PipelineContext.contains(" + args.get(0) + ", " + args.get(1) + ")";
            case "trim":     return "PipelineContext.trim(" + args.get(0) + ")";
            case "replace":  return "PipelineContext.replaceStr(" + args.get(0) + ", " + args.get(1) + ", " + args.get(2) + ")";
            case "sort":     return "PipelineContext.sortArray(" + args.get(0) + ")";
            case "map":      return "PipelineContext.mapArray(" + args.get(0) + ", " + args.get(1) + ")";
            case "filter":   return "PipelineContext.filterArray(" + args.get(0) + ", " + args.get(1) + ")";
            case "reduce":   return "PipelineContext.reduceArray(" + args.get(0) + ", " + args.get(1) + ", " + args.get(2) + ")";
            case "upper":    return "PipelineContext.toStr(" + args.get(0) + ").toUpperCase()";
            case "lower":    return "PipelineContext.toStr(" + args.get(0) + ").toLowerCase()";
            case "startsWith": return "PipelineContext.toStr(" + args.get(0) + ").startsWith(PipelineContext.toStr(" + args.get(1) + "))";
            case "endsWith": return "PipelineContext.toStr(" + args.get(0) + ").endsWith(PipelineContext.toStr(" + args.get(1) + "))";
            case "substring": return args.size() > 2
                ? "PipelineContext.toStr(" + args.get(0) + ").substring(PipelineContext.toInt(" + args.get(1) + "), PipelineContext.toInt(" + args.get(2) + "))"
                : "PipelineContext.toStr(" + args.get(0) + ").substring(PipelineContext.toInt(" + args.get(1) + "))";
            case "indexOf":  return "PipelineContext.toStr(" + args.get(0) + ").indexOf(PipelineContext.toStr(" + args.get(1) + "))";
            case "abs":      return "Math.abs(PipelineContext.toNum(" + args.get(0) + "))";
            case "round":    return "Math.round(PipelineContext.toNum(" + args.get(0) + "))";
            case "floor":    return "Math.floor(PipelineContext.toNum(" + args.get(0) + "))";
            case "ceil":     return "Math.ceil(PipelineContext.toNum(" + args.get(0) + "))";
            default:         return name + "(" + String.join(", ", args) + ")";
        }
    }

    // ============================================================
    // Helpers
    // ============================================================

    private String generateInvokeCall(ServiceRefContext serviceRef, ArgumentListContext argList) {
        String svcName = serviceRef.getText();
        StringBuilder sb = new StringBuilder();
        sb.append("PipelineContext.invoke(\"").append(escape(svcName)).append("\"");

        if (argList != null) {
            for (ArgumentContext arg : argList.argument()) {
                String paramName = arg.argumentName().getText();
                String value = visit(arg.expression());
                sb.append(", \"").append(escape(paramName)).append("\", ").append(value);
            }
        }

        sb.append(")");
        return sb.toString();
    }

    private String generateNestedSet(String target, String value) {
        String[] parts = target.split("\\.");
        if (parts.length == 2) {
            String root;
            if (localVars.contains(parts[0])) {
                root = parts[0];
            } else {
                root = "ctx.get(\"" + escape(parts[0]) + "\")";
            }
            return indent() + "PipelineContext.setField(" + root
                 + ", \"" + escape(parts[1]) + "\", " + value + ");\n";
        }

        // Deep nesting: navigate to parent, then set field
        StringBuilder sb = new StringBuilder();
        String parentVar = newTempVar("parent");
        sb.append(indent()).append("Object ").append(parentVar).append(" = ");

        String root;
        if (localVars.contains(parts[0])) {
            root = parts[0];
        } else {
            root = "ctx.get(\"" + escape(parts[0]) + "\")";
        }

        if (parts.length == 3) {
            sb.append("PipelineContext.getField(").append(root)
              .append(", \"").append(escape(parts[1])).append("\");\n");
        } else {
            sb.append("PipelineContext.getPath(").append(root);
            for (int i = 1; i < parts.length - 1; i++) {
                sb.append(", \"").append(escape(parts[i])).append("\"");
            }
            sb.append(");\n");
        }

        sb.append(indent()).append("PipelineContext.setField(").append(parentVar)
          .append(", \"").append(escape(parts[parts.length - 1]))
          .append("\", ").append(value).append(");\n");
        return sb.toString();
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }
}
